const NEW_TAIPEI_CITY = {
  banqiao: "板橋",
  zhonghe: "中和",
  yonghe: "永和",
  wanli: "萬里",
  jinshan: "金山",
  xizhi: "汐止",
  shenkeng: "深坑",
  shiding: "石碇",
  ruifang: "瑞芳",
  pingxi: "平溪",
  shuangxi: "雙溪",
  gongliao: "貢寮",
  xindian: "新店",
  pinglin: "坪林",
  wulai: "烏來",
  tucheng: "土城",
  sanxia: "三峽",
  shulin: "樹林",
  yingge: "鶯歌",
  sanchong: "三重",
  xinzhuang: "新莊",
  taishan: "泰山",
  linkou: "林口",
  luzhou: "蘆洲",
  wugu: "五股",
  bali: "八里",
  tamsui: "淡水",
  sanzhi: "三芝",
  shimen: "石門",
}

export { NEW_TAIPEI_CITY }
